### ISSUE TITLE
Given that I'm a broker or buyer, when I go to the users page, I should not see all users.

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/stock-transfer-app#27]
### Tasks

- [x] Add method to check if user is an admin
- [x] Specify user list restriction for users who who are not admin
- [x] Update user controller to check if user is admin before index action
