### ISSUE TITLE
The system should have user status of pending or approved.

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/stock-transfer-app#36]
### Tasks
- [x] Specify user status
- [x] Update user to include status of pending and approved
- [x] The system should automatically assign user status of approved if user role is buyer
- [x] The system should automatically change user status to pending if user role is broker
