### ISSUE TITLE
Given that I'm a buyer, when I go to the stocks page, I should be able to search stocks.

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/stock-transfer-app#57]
### Tasks

- [x] Specify stock search
- [x] The system validates whether the stock is valid
- [x] Generates an error message when the stock field is blank
- [x] Generates an error message when the stock is not valid
