### ISSUE TITLE
Given that I'm a broker, when I go to the stocks page, and enter the amount of shares to be sold, the shares can be bought by the buyers.

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/stock-transfer-app#60]
### Tasks

- [x] Specify offer model
- [x] Offer table accepts stock id, user id, price, shares, status (open, closed, cancelled), order type (limit order and market order), action (buy or sell)
- [x] Specify trade model
- [x] Trade table accepts stock id, buyer_id, seller_id, price, shares, offer_ids
- [x] Given that I'm a broker, when I go to the stocks page, select market order, enter the amount of shares to be bought. The shares are sold at the current market price and my balance decreases based on the amount sold.
