### ISSUE TITLE
Given that I am an admin user, when I go to the create users page, enter the first name, last name, email and password of the user; and click the Sign up button, the system should generate a success message and display the data associated with the account.

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/stock-transfer-app#9]
### Tasks
- [x] Add devise gem
- [x] Specify user creation
- [x] Add user model
- [x] Add user controller
- [x] Add create user page
